### PR TITLE
Add instant previews on now.sh

### PR DESCRIPTION
**Pull request by honzajavorek**
Blocked by https://github.com/pyvec/docs.pyvec.org/pull/104, closes https://github.com/pyvec/docs.pyvec.org/issues/106

### CODE REVIEW

**Comment by honzajavorek** [comment]
If the bot feels too talkative with its comments, they can be turned off. But since this hasn't been merged yet and the comments aren't useful *yet*, they might feel annoying just for the reason they're not relevant. That's why I'd wait with turning it off until after we merge this and see if they're actually helpful when it's all working.

**Comment by honzajavorek** [comment]
To Do: After merging & deploying we should check that the `pyvec-guide.readthedocs.io` redirect still works.

**Comment by honzajavorek** [comment]
Merging. I wanted @messa to review this as an experienced now.sh experimenter, but I don't want to hold #98 away from reviewing any longer. If there's something, anyone is invited to comment on the merged PR and let's fix it in a subsequent PRs.

**Comment by messa** [comment]
Btw. zjistil jsem, že když nasazuju přes `now` (jiný projekt, ne tenhle), tak to zakládá lambdy někde v us-west, přestože v dokumentaci now píšou, že se mají dělat geograficky nejblíže, kde jsem já (a přitom nemám žádnou VPN ani proxy). Pomohlo `now --regions bru1`, nebo to [nakonfigurovat v now.json](https://zeit.co/docs/configuration/#project/regions)

**Comment by honzajavorek** [comment]
Hmmm. Dobrý vědět. Poslal bys na to sem PR?

**Comment by honzajavorek** [comment]
Nooo, ale

> This value does not impact static files or edge caches, since deployments always have a CDN layer in front.

A tady se nasazují jen statické soubory.

**Pull request merged**
